server:
  port: 8001

# mybatis配置
mybatis:
  # mybatis配置文件
  config-location: classpath:mybatis/mybatis-config.xml
  # mybatis mapper文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.renthouse.pojo

# spring配置
spring:
  application:
    name: springcloud-provider
  # spring连接数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/renthouse?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root